-- Widen ALL VARCHAR columns to support UUIDs and longer category names
ALTER TABLE budgets
ALTER COLUMN user_id TYPE VARCHAR(50),
ALTER COLUMN budget_id TYPE VARCHAR(50),
ALTER COLUMN category TYPE VARCHAR(100);

ALTER TABLE transactions
ALTER COLUMN user_id TYPE VARCHAR(50),
ALTER COLUMN transaction_id TYPE VARCHAR(50),
ALTER COLUMN category TYPE VARCHAR(100),
ALTER COLUMN description TYPE VARCHAR(500),
ALTER COLUMN type TYPE VARCHAR(20);

ALTER TABLE users
ALTER COLUMN user_id TYPE VARCHAR(50),
ALTER COLUMN full_name TYPE VARCHAR(200),
ALTER COLUMN email TYPE VARCHAR(200),
ALTER COLUMN phone TYPE VARCHAR(50),
ALTER COLUMN college TYPE VARCHAR(200),
ALTER COLUMN course TYPE VARCHAR(200),
ALTER COLUMN year TYPE VARCHAR(20),
ALTER COLUMN city TYPE VARCHAR(100),
ALTER COLUMN profile_image TYPE TEXT;
